using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication1
{
    class Constants
    {
        public static string[] Tickers = new[]
        {
            "ANH", "ANK", "ATNI", "AVD", "BCPC", "BCP", "BMI", "BNE", "BTI", "BTJ", "BOLT", "CAC", "CAS", "CASL", "CBJ",
            "CUB", "CVBF", "CVC", "NXY", "CYP", "QCOR", "QSC", "DIA", "DRS", "DVN", "LCII", "DW", "BNN", "EBC", "BAM",
            "EE", "EWA", "EWC", "EWD", "EWG", "EWH", "EWI", "EWJ", "EWK", "EWL", "EWM", "EWN", "EWP", "EWQ", "EWS",
            "EWU", "EWW", "GHM", "GRC", "GTA", "PTX", "HAS", "HH", "HFC", "HOC", "HT", "IDCCD", "IDC", "IDCC", "IMPH",
            "IMH", "IMPM", "IMO", "JST", "LDR", "LGF", "LGF/A", "MDY", "MEG", "MYE", "NAT", "NRG", "NTI", "OLP", "PPD",
            "PRK", "PSB", "QQQQ", "QQQ", "RAS", "RBC", "SGC", "SJW", "SPY", "STS", "TAM", "TDS", "KAI", "TMP", "TTP",
            "UMH", "UTL", "VIA", "VIA/B", "VIA'B", "XLB", "XLE", "XLF", "XLI", "XLK", "XLU", "XLV", "XLY", "AAPL",
            "ABAX", "ABCB", "ARCB", "ABFS", "ACAS", "ACAT", "ACET", "ATN", "ACXM", "ADBE", "ADELQ", "ADLAE", "ADSK",
            "ADTN", "ADVNA", "ADVNB", "ADVBQ", "ADVS", "ADVSE", "AEO", "AEOS", "SWKS", "AHAA", "AKZOY", "ALDN", "AXB",
            "ALEX", "MATX", "ALD", "ALOG", "RLRN", "ALTR", "AMAT", "AMFI", "AMFIQ", "AMGN", "AMNB", "AMSWA", "AMTD",
            "AMWD", "ANAT", "ANDE", "ANLY", "APCC", "APOG", "APSG", "AROW", "ARRO", "ARTNA", "ASBC", "ASB", "ASCA", "AF",
            "ASFI", "ASTE", "ATML", "ATYT", "BAMM", "BARZ", "BBBY", "BBOX", "BBSI", "BEAV", "BEBE", "BEIQ", "BELFB",
            "CHBS", "BFCI", "CBK", "WRB", "BER", "BKUNA", "BKUNQ", "BLGM", "BLG", "BLGME", "BMHC", "BMTC", "BOBE",
            "BOKF", "BONT", "BOOM", "BPFH", "BPOP", "BRCM", "BRKLD", "BRKL", "BRKS", "BSET", "BUSE", "BWINB", "CACBD",
            "CACB", "CTR", "CATO", "TSFG", "CAFC", "CAKE", "CALM", "CASS", "CASY", "CATY", "CBCF", "CRBC", "CRBCD",
            "CBRL", "CBSH", "CBSS", "CBUK", "CBUKE", "CCNE", "CCUR", "CDRD", "SIRI", "CECE", "CENX", "CFBX", "CFFN",
            "CFFND", "CGNX", "CHCO", "CHFC", "CHKE", "CHRS", "CHRWD", "CHRW", "CHUX", "CINF", "CGI", "CLDN", "CLTK",
            "CMCO", "CMCS'A", "CMCSA", "CMCSK", "CMTL", "CMN", "CMD", "CNXS", "COBZ", "COHU", "COLB", "COLM", "CORS",
            "CORSQ", "COST", "CPWR", "CRAI", "CRDN", "CRRC", "CSCO", "CSGS", "OUTR", "CSTR", "CSWC", "CTBI", "CTCO",
            "HKTV", "HKTVY", "CTEL", "CTWS", "CWCO", "DAKT", "IDCO", "DCOM", "DELL", "DMLP", "DHULZ", "DKHR", "DKWD",
            "DORL", "DRL", "DRRA", "DRRAQ", "DRYR", "DTPI", "EASI", "ECIL", "ECILF", "ECOL", "ELRC", "EME", "EMCI",
            "EMMS", "EPIQ", "ERIE", "ESCA", "ESLT", "EVOL", "EWBC", "EXPD", "EXPO", "EZPW", "FAST", "FBNC", "FCFS",
            "FCNCA", "FCTR", "FDEF", "FEIC", "FELE", "FFBC", "FFCH", "FFIC", "FFIN", "FINL", "FITB", "FBC", "FMBI",
            "FMER", "FNBN", "COB", "FRDM", "FRM", "FRED", "FRME", "FSTR", "FTBK", "FTBKD", "FULL", "FUL", "FULT", "BANR",
            "BANRD", "GABC", "GBBK", "GBCI", "GBCOA", "GEF", "GILD", "GLDB", "GMCR", "GLF", "GMRK", "GNTX", "GSBC",
            "HBAN", "HBHC", "HCSG", "HDNG", "HELX", "HFWA", "HNBC", "HOTT", "HSII", "HTBK", "HTLD", "HWKN", "IBCP",
            "IBOC", "ICBC", "IDT'C", "IDT/C", "IFIN", "TILE", "IFSIA", "IMKTA", "INDB", "INFY", "INMT", "STEL", "INTC",
            "INTL", "INTU", "INVX", "IPCR", "IFC", "IBKC", "ISBF", "ISSI", "ISYS", "MSFG", "JAKK", "JBHT", "JJSF",
            "JKHY", "KBAL", "KBALB", "KELYA", "VIVO", "KLAC", "KNX", "KNGT", "KNSY", "KSWS", "LABL", "LAMR", "LANC",
            "LCAVD", "LCAV", "LCUT", "LNYI", "LNY", "LECO", "LFUS", "LION", "LKFN", "LLTC", "LNCE", "LNCR", "LRCX",
            "LSTR", "LUFK", "LYTS", "MAFB", "SM", "MARY", "MATW", "MCHP", "MCRL", "MDCA", "MGEE", "MDSN", "MEOH",
            "MERCS", "MERC", "MEI", "METHA", "METH", "MGRC", "MIK", "MINI", "MLHR", "MNES", "MSA", "MNRO", "MNTR", "MNT",
            "MOLXE", "MOLX", "MOLAE", "MOLXA", "MOV", "MOVI", "MOVIQ", "MRBK", "MRIS", "MI", "MRTN", "MSEX", "MSFT",
            "MTEX", "MTSC", "MTSCE", "MWGP", "MGPI", "MXIM", "NAFCE", "NAFC", "HOPE", "NARAE", "NARA", "BBCN", "NASI",
            "NATI", "NAVG", "FNFG", "NBCP", "FNFGD", "NBTB", "NCEN", "NEWCQ", "NEWC", "NEW", "NDSN", "NETP", "NEWP",
            "NICE", "NNBR", "NOOF", "NPBC", "NTP", "NTAI", "NTE", "NTAP", "NTBK", "NTBKQ", "NTRS", "NUTR", "NVDA",
            "NWNG", "NWN", "NWBI", "NWSB", "OCAS", "OCFC", "ODFL", "ODIS", "EXLND", "EXLN", "OKSB", "ONB", "OPTN",
            "ORCL", "OSBC", "OSI", "OSSI", "OTEX", "OSK", "OTTR", "OHP", "OZRK", "PAAS", "PHX", "PANRA", "PATK", "PAYX",
            "PBCT", "PBCTD", "PBKS", "PCAR", "PDCO", "PDLI", "PEBO", "PEGA", "PETM", "PFCB", "PFGI", "PHBK", "BKNG",
            "BKNGD", "BNK", "PIOS", "PKOH", "PLMD", "PMFG", "POOL", "POWI", "POWL", "PPDI", "PRGS", "PB", "PRSP", "PSEM",
            "PSMT", "PTEN", "PULB", "PZZA", "QCRH", "QCOM", "NYB", "NYCB", "QSII", "QWST", "Q", "RBCAA", "RBNC", "RCII",
            "RELL", "REXI", "RGBK", "RF", "RGFC", "RGFCQ", "RGF", "RGIS", "RGS", "RGLD", "RIGS", "QUMU", "RIMG", "RMBS",
            "ROAD", "ROCK", "ROMC", "KFRC", "ROST", "RSLN", "RTRSY", "TRIN", "RVSB", "SABB", "PCBCD", "PCBC", "SAFC",
            "SAF", "SAFM", "SASR", "SBCF", "SBGI", "SBIB", "SBSI", "SBUX", "SCHL", "SCHN", "SCIX", "SCIXF", "SCOR",
            "SCVL", "SEBL", "SEIC", "SGNT", "SHLM", "SIAL", "SIGI", "SKYW", "SKYWE", "SLGN", "SLNK", "SMRT", "SNBC",
            "SNDK", "SNHY", "SONC", "SOTR", "SPAR", "SPGLE", "SRCE", "SSNC", "SVC", "SSSS", "STAR", "STBA", "STEI",
            "STFC", "GVHR", "STLD", "STRA", "STSA", "STSAD", "STST", "STTX", "SUBK", "SCNB", "MENS", "SUIT", "TLRD",
            "MW", "SUSQ", "SOV", "SWBT", "ABNK", "SYGR", "SYMC", "SYNL", "SYNC", "SYNT", "SYPR", "TACT", "TALX", "TALXE",
            "TNC", "TARRQ", "TARR", "MFIN", "TAXI", "TCBK", "TECH", "TECU", "TECUA", "TEVA", "TEVIY", "THFF", "TMBS",
            "TOPP", "TRMK", "TROW", "TRST", "CCI", "ASRV", "UBSH", "UBSI", "UCBH", "UCBHQ", "UCFC", "UFCS", "UFPI",
            "UHAL", "UMBF", "UMPQ", "KMPR", "UTR", "IAC", "IACI", "IACID", "USAI", "USFC", "VALM", "VMI", "VICR", "WABC",
            "WASH", "TTEK", "WHI", "WHCI", "WBS", "WBST", "WCBOD", "WCBO", "WCN", "WCNX", "WDFC", "WERN", "WFM", "WFMI",
            "WFSL", "WAFD", "WWD", "WGOV", "WIRE", "WRLS", "WSBC", "WSFS", "WTFC", "WTNY", "XLNX", "XRAY", "ZEUS",
            "ZION", "AA", "ABC", "AAS", "ABF", "ABK", "ABKFQ", "ABM", "ABN", "ABNYY", "ABS", "ABT", "ABX", "AC", "AB",
            "CB", "ACL", "ACE", "ACO", "AD", "ADC", "ADI", "ADM", "AEC", "AEE", "AEG", "AEP", "AES", "AFG", "AFL",
            "AGCO", "AG", "AGC", "AGE", "AGN", "HES", "AHC", "AHOw", "AHO", "ADRNY", "AHONY", "AHOND", "ADRND", "AHP",
            "WYE", "ACPIQ", "AHR", "ACPI", "AIB", "AIBYY", "AIG", "AIN", "AIR", "AIV", "AJG", "AKR", "AL", "ALB", "JAH",
            "HON", "ALG", "ALK", "ALL", "ALO", "ALV", "AM", "AMB", "AME", "AMG", "AMN", "AON", "AOC", "AOL", "TWX",
            "AOS", "AP", "APA", "APC", "APD", "APH", "APU", "ARA", "ARE", "ARG", "ARJ", "ASA", "ASD", "TT", "ASH", "ASN",
            "ASO", "AT", "GAS", "ATG", "AGL", "ATO", "ATR", "ATW", "AU", "ADP", "AVB", "AVX", "AVY", "IVZ", "AVZ", "AWK",
            "AWR", "AXL", "AXP", "AYE", "AZN", "AZZ", "B", "BA", "ICAGY", "BAB", "BAIRY", "BAC", "BBT", "BBV", "BBVA",
            "BBX", "BBY", "BC", "OMX", "BCC", "BCE", "CM", "BCM", "BCR", "BCS", "BDK", "BDN", "BDX", "BEC", "BEN", "BEZ",
            "BF/A", "BFA", "BF/B", "BFB", "BGG", "BHI", "BHP", "BID", "BJS", "BK", "BKE", "BKH", "BKI", "BKS", "BLC",
            "BLK", "BLL", "BLS", "BLX", "BMO", "BMS", "BMY", "BNI", "BOH", "BOL", "BOW", "BOX", "BPL", "BPT", "BR",
            "BRE", "BRGYY", "BRG", "BRY", "BSC", "BTH", "BUD", "BVC", "GLK", "BVF", "VRX", "BVN", "BW", "MTRN", "BWA",
            "BWC", "BXP", "BXS", "BYD", "BZH", "C", "CA", "CASC", "CAE", "CAG", "CAH", "CAR", "CAT", "CBD", "CBE", "CBH",
            "CBI", "CBL", "CBM", "CBT", "CBU", "CCTYQ", "CC", "CCC", "CCE", "CCJ", "CCL", "CFC", "CCR", "CCU", "CD",
            "CDI", "CDO", "CDT", "BDC", "CDX", "CEA", "CEI", "CFB", "CFR", "CHD", "CHK", "CHL", "CHHPD", "CHP", "CHHP",
            "CVX", "CHV", "CHZ", "CI", "CIB", "CIN", "CKR", "CL", "CLB", "CLC", "CLE", "CLF", "CLI", "CLP", "CLX", "CMA",
            "CMC", "CMH", "CMS", "CNA", "CBCGQ", "CBCG", "CNB", "CNC", "CNW", "CNF", "CNI", "CNL", "BIG", "BLI", "CNS",
            "COC'A", "COF", "COG", "COO", "COX", "CP", "CPB", "CPC", "CPK", "PGN", "CPL", "CPO", "INGR", "CPQ", "CPT",
            "CQB", "CR", "CRDA", "CRD/A", "CRK", "CRS", "CRY", "CSC", "CSKE", "CSK", "CSKEQ", "CSL", "CSV", "CSX", "CT",
            "BXMT", "CTB", "CTC", "CTMCY", "CTL", "CTS", "CTX", "CUM", "CMI", "CUZ", "CVG", "CVS", "CW", "CWP", "CWT",
            "CY", "CYD", "CYN", "CZN", "FTR", "D", "DAL", "DBD", "DCI", "DCNAQ", "DCN", "DCO", "DD", "DDR", "DDS", "DE",
            "DEL", "DEO", "DFDEL", "DFG", "DG", "DGX", "DHI", "DHR", "DJ", "DL", "DLM", "DLP", "DLX", "DME", "DNB",
            "DNR", "DNY", "RRD", "DO", "DOMR", "DOM", "DOV", "DOW", "DOX", "DP", "DPHIQ", "DPH", "DPL", "DQE", "DRE",
            "DRI", "DSL", "DWNFQ", "DST", "DTC", "UFS", "DTE", "DUK", "DV", "DVD", "DYN", "DYNIQ", "E", "EAT", "EBF",
            "EC", "ECL", "ED", "EDE", "EDO", "EDS", "EFX", "EGN", "EGP", "EKDKQ", "EK", "EL", "ELK", "ELY", "EMC", "EMN",
            "EMR", "EMT", "ENE", "ENI", "ENIA", "ENN", "EOCC", "EOC", "EOG", "EOP", "EPD", "EPG", "EP", "EPR", "EQR",
            "EQT", "EQY", "ESE", "ESS", "ESV", "ETH", "ETM", "ETN", "EV", "F", "CLGX", "FAF", "FBNIQ", "FBN", "FBNI",
            "FBP", "FCEA", "FCE/A", "FCF", "FCH", "FCX", "M", "FD", "FDC", "FDO", "FDP", "FDS", "FDX", "FE", "FFG",
            "FGP", "FIC", "FICO", "FII", "FLA", "FLTQE", "FLE", "FLTWQ", "FLTWE", "FLTW", "FLM", "FLMIQ", "MEE", "FLS",
            "FMC", "SGGH", "FMT", "SGGHU", "FMNT", "FMNTQ", "FMX", "FNF", "FNMA", "FNM", "FO", "BEAM", "FOE", "FON", "S",
            "FPL", "NEE", "FR", "FMCC", "FRE", "FRK", "FRT", "FS", "FSS", "FTE", "ORAN", "FTO", "FUN", "FVB", "FVH",
            "OPY", "FWLT", "FWC", "G", "GAP", "GAPTQ", "GBX", "GCI", "TGNA", "GCO", "GTN", "GCS", "GD", "GDI", "GDT",
            "GDW", "GE", "GEL", "RHP", "GET", "GFF", "GG", "GGB", "GGC", "AXLL", "GGG", "GGP", "GGWPQ", "GIS", "GLC",
            "GLH", "GLT", "GLW", "GSK", "GMGMQ", "MTLQQ", "GM", "GATX", "GMT", "GP", "GPC", "GPI", "GPS", "GPT", "GPU",
            "GR", "GRA", "GRB", "GRT", "GSB", "GT", "GTK", "GTY", "GVA", "GWW", "AJRD", "GY", "HAL", "HAR", "HRC", "HB",
            "HCC", "HCN", "HCP", "HCR", "HD", "HOG", "HDI", "HDLM", "HDL", "HE", "HET", "HF", "HHS", "HI", "HIB", "HIG",
            "HIT", "HTHIY", "HIW", "HL", "SUTM", "SVN", "HLR", "SUTMQ", "HLT", "HMA", "HMC", "HME", "HMN", "HMT", "HST",
            "HNI", "HNZ", "HOT", "HP", "HPC", "ETP", "HPG", "HPT", "HR", "HRB", "HLS", "HLSH", "HRH", "HRL", "HRS",
            "HSC", "HSY", "HTV", "HUB/B", "HUBB", "HUG", "HUM", "HVT", "HPQ", "HWP", "HXL", "IBC", "IBCIQ", "IBI", "IBM",
            "IBP", "ICI", "ICIYY", "ICN", "IDA", "IDR", "IEX", "IFF", "IFN", "IGL", "IGT", "IIF", "III", "IIIN", "IKN",
            "IM", "IMN", "ING", "INT", "IP", "IPG", "IPS", "IR", "IRE", "IREBY", "IRS", "ISP", "MT", "IST", "ITW", "JBL",
            "JCI", "JCP", "JEC", "JEF", "JLG", "JLL", "JNC", "JNJ", "JNY", "JOE", "JP", "JPM", "JRCOQ", "JRC", "JRCO",
            "JWA", "JW/A", "K", "KBH", "KCP", "KDN", "KEI", "KEY", "KGC", "KIM", "KLM", "GXP", "KMB", "KMG", "KMT", "KO",
            "KR", "KRB", "KRC", "KRI", "KSE", "KSU", "KTO", "KUB", "KUBTY", "KWD", "KWR", "LAD", "LAF", "LYBI", "LBY",
            "LDG", "LEARQ", "LEAR", "LEA", "LEE", "LEG", "LEHMQ", "LEH", "LEN", "LFB", "LFG", "LFGRQ", "LFL", "LG", "SR",
            "LHO", "EEP", "KATE", "LIZ", "FNP", "LLY", "LM", "LMT", "LNC", "LNN", "LNR", "LNT", "LOW", "LPX", "LPT",
            "LRY", "LSI", "LTC", "LTD", "LB", "LTR", "L", "LU", "LUB", "LUV", "LXK", "LXP", "LYO", "LZ", "LZB", "MAA",
            "MAC", "PRA", "MAN", "MAR", "MAS", "MAT", "MAY", "MBI", "PC", "PCRFY", "MC", "MCD", "MCH", "MCK", "MCL",
            "MWI", "MCS", "MCY", "MDC", "MDP", "MDR", "MDS", "MDT", "MDU", "MEL", "MER", "MFA", "MGA", "MGM", "MHO",
            "MHP", "MHFI", "SPGI", "MHX", "MIG", "MIL", "MLM", "MLR", "MLS", "MM", "MMC", "MMM", "MMR", "MMS", "MNC",
            "MCOA", "MCOAQ", "MNI", "MO", "MOT", "MSI", "ALE", "MPL", "MRD", "MRK", "MRO", "MRX", "MSB", "MASC", "MSC",
            "MSM", "MTB", "MTC", "PHA", "MTG", "MTN", "TAA", "MTW", "MTX", "MUR", "MS", "MWD", "MXF", "MYG", "MYL",
            "INCLF", "N", "NAV", "NAVZ", "NBL", "OKS", "NBP", "NCC", "NCX", "NDC", "IMB", "IDMC", "IDMCQ", "NDE", "NE",
            "EAS", "NEG", "NEM", "NRT", "NFB", "NFG", "NOVC", "NOVCQ", "NOVS", "NFI", "NFS", "NHI", "NHP", "NI", "NJR",
            "NL", "NLY", "NMG/A", "NMGA", "NMG", "NNN", "NNS", "NOC", "NOV", "NOI", "NOR", "NSC", "NSI", "NSM", "NRTLQ",
            "NT", "NTT", "ES", "NU", "NUE", "NUS", "NVO", "NWL", "NWS", "FOX", "NX", "NYT", "NZT", "NZTCY", "SPKKY", "O",
            "OCR", "ODP", "OEI", "OFC", "OFG", "COV", "OGE", "OHI", "OII", "OKE", "OLN", "OMC", "OME", "OMI", "OMM",
            "ONE", "ORI", "OS", "OSG", "OSGIQ", "OXM", "OXY", "P", "COP", "PAA", "PBG", "PBI", "PBT", "PBY", "PCG",
            "PCH", "PCP", "SCCO", "PCU", "PCZ", "PD", "PDG", "EXC", "PE", "PEG", "PEI", "PEO", "PEP", "PFE", "PG", "PGL",
            "PGR", "PH", "PHI", "PHM", "PII", "PIR", "PKE", "SIX", "SIXFQ", "PKS", "SIXF", "PKX", "PKY", "PL", "PLD",
            "PLL", "PLT", "PNC", "PNM", "PNR", "PNW", "PNY", "POG", "POM", "PTBT", "PTBTQ", "POP", "POT", "PPG", "PPL",
            "PPP", "PPS", "PRD", "PRE", "PRM", "PSA", "PSC", "WTR", "PSD", "PTGCY", "PT", "PVAH", "PVA", "PVAHQ", "PVH",
            "PVN", "CSH", "PWN", "PX", "AGIID", "PXT", "AGII", "PZB", "BCO", "PZL", "CXW", "PZN", "R", "RA", "RAL",
            "RBA", "RBN", "RCL", "RD", "RDA", "RDC", "RDK", "HTSI", "RE", "REG", "REP", "REPYY", "RES", "REY", "RCI",
            "RG", "RGA/A", "RGA", "RGR", "RT", "RI", "RIG", "RJF", "RKT", "TAP", "RKY", "RL", "RLI", "RML", "RNR", "AAN",
            "RNT", "ROH", "ROK", "ROL", "ROP", "AVE", "RP", "RPM", "RPT", "RRC", "RS", "RSE", "RSG", "RYI", "RTN", "RIO",
            "RTP", "KIDBQ", "KIDB", "KID", "RUS", "RWT", "RX", "RY", "RYL", "RYN", "SAH", "SBC", "T", "SBL", "SC",
            "SCHW", "SCH", "SCL", "SCR/A", "SCRA", "GSF", "SEE", "SEH", "SF", "SFA", "SFG", "SGI", "SGP", "SGU", "SHS",
            "SHW", "SIB", "SID", "SJI", "SJR", "SJT", "SKM", "SKT", "SLB", "HSH", "SLE", "SLG", "SLI", "SLM", "SMG",
            "SMP", "SNA", "SNE", "SNV", "SO", "SON", "SPA", "SPC", "STA", "TRV", "CAA", "SPF", "SPG", "SPH", "SPW",
            "SPXC", "SQM", "SRE", "SRP", "NVE", "SRR", "SRT", "SRV", "SCI", "SSD", "SSP", "SSS", "STC", "SAN", "STD",
            "STE", "STI", "STJ", "STL", "STM", "STN", "STR", "STT", "SU", "SUG", "SUI", "SUN", "SUP", "SUT", "SVM",
            "SVU", "SWK", "SWM", "SWN", "SWS", "SWX", "SWY", "SXI", "SYK", "SYY", "TAR", "TBH", "TCB", "TCO", "VIV",
            "TCP", "TD", "TDW", "TE", "TEF", "TEK", "TEN", "TEO", "TER", "TFX", "TG", "TGI", "THO", "TIE", "TIF", "TIN",
            "TJX", "TK", "TKR", "TLB", "TLK", "TLM", "THMRQ", "TMA", "THMR", "TMK", "TMX", "TNB", "TNH", "TNL", "PULS",
            "TOS", "TOT", "TPP", "TR", "TRA", "TRB", "TRH", "TRN", "TRP", "TRW", "WEN", "TRY", "TSG", "CTG", "CTGX",
            "TSN", "TSO", "TSP", "TSS", "TSU", "TTC", "TUP", "TWI", "TWR", "TX", "TXI", "TXN", "TXT", "TXU", "TY", "TYC",
            "TZA", "TZH", "UAG", "PAG", "UAL", "UALAQ", "UBB", "UCL", "ILA", "UDR", "UDS", "SXT", "UGI", "UHS", "UHT",
            "UIC", "UIL", "UL", "UN", "UNF", "UNH", "UNP", "UNS", "UPC", "URS", "USB", "USG", "USI", "UST", "USU", "UTX",
            "UVV", "VAL", "VCI", "VFC", "VHI", "VLO", "VLY", "VMC", "VNO", "VNT", "VOD", "VPI", "VTA", "VTR", "VVI",
            "MWV", "MEA", "WAB", "WAG", "WBA", "WCS", "WDR", "WEC", "WFC", "WGL", "WGO", "WGR", "PAS", "WHR", "WIN",
            "WL", "WLL", "WLTGQ", "WLT", "WLTG", "WAMUQ", "WM", "WMB", "AWC", "AWCMY", "WMC", "WMT", "WNC", "SHF", "WNI",
            "WON", "DIAL", "WWOZ", "WWON", "ACT", "WPI", "TEG", "WPS", "WR", "WRE", "WRI", "WSO", "WST", "WTS", "WWW",
            "WWY", "WXH", "WY", "X", "XL", "XRX", "XTO", "YRK", "YUM", "Z", "FL", "ZNH", "ZNT", "AN", "BLOAQ", "BLOKA",
            "BBI", "BGC", "BWS", "CAL", "CMX", "CEMJQ", "CEM", "CK", "CNX", "COC'B", "EGOV", "FBF", "GS", "ITG", "JBX",
            "JACK", "JNPR", "JWN", "MBG", "MXT", "RAI", "RJR", "RMD", "SYX", "TM", "TSCM", "TST", "UCI", "CEG", "ABI",
            "PKI", "ATI", "BRCD", "BRCDD", "BRCDE", "XOM", "A", "HBC", "HSBC", "ALSK", "ARLP", "CLCT", "CLCTD", "FISI",
            "HCBK", "JCOM", "JFAX", "KEYN", "LAB", "LII", "LQID", "NEU", "UNTD", "PCTI", "PTNR", "PVTB", "TRLY", "TRRA",
            "UPS", "VIAN", "WWF", "WWE", "STZ", "CDB", "KMP", "SHPG", "SHPGY", "PMI", "PPMIQ", "HHHYL", "HHH", "AKS",
            "APL", "TSTN", "DCEL", "ELNK", "ELNKD", "NXL", "AVT", "GLCBY", "NETCD", "NETC", "BBH", "BBHH", "BBHYL",
            "OLG", "BRS", "OLOG", "AVA", "AVP", "BPA", "BP", "ELE", "ELEYY", "ESA", "ETR", "KIDD", "GDYS", "HU", "NKE",
            "CVH", "PCL", "RBK", "TEX", "TGT", "UNM", "NATR", "WSM", "YPF", "AET", "ACV", "EIX", "CNP", "REI", "FUR",
            "PTR", "PLB", "AITP", "AIPC", "SCS", "SCS'A", "XLP", "MET", "DDIC", "ABY", "AI", "FBR", "WDC", "WOR", "VGR",
            "HCA", "RSHC", "RSH", "RSHCQ", "ESPD", "BGCP", "ISIL", "PCBK", "BOO", "RBI", "RHI", "CF", "CKSWE", "CKSW",
            "SLC", "SLF", "VC", "VSTNQ", "VSTN", "VZ", "CKCM", "CKCMD", "MRVL", "NTESE", "NTES", "PPH", "PPHYL", "PBU",
            "EPC", "ENR", "SMH", "SMHYL", "SAE", "MBT", "MTOR", "ARM", "TKC", "SV", "JNS", "BHH", "TTH", "TTHYL", "IIH",
            "IAH", "BDH", "HRP", "CWH", "EQC", "LQI", "RKHYL", "RKH", "RBJ", "UTH", "UTHYL", "XRIT", "ERJ", "WEBX",
            "OPNT", "EVC", "OEH", "BEL", "NLS", "XEL", "BRO", "ITT", "PBR", "CAJ", "CANNY", "POL", "ABEV", "ABV", "UMC",
            "PRTN", "ASX", "MCO", "OPLK", "COH", "TW", "WW", "MON", "MKH", "WIT", "WRC", "ALAO", "SWH", "SWHYL", "SNP",
            "TU", "ERPLQ", "EPL", "ERPL", "V", "BKMU", "WMH", "IXYS", "SYXI", "IWO", "AGM", "AGU", "AIT", "BPO", "CFI",
            "CIR", "CLU", "CMO", "CRR", "DOL", "EPN", "EX", "FTN", "FHN", "WPSL", "WPSLF", "WPL", "GRMN", "KMI", "RECN",
            "FLR", "MONI", "IWB", "IWM", "IWN", "NWS'A", "NWSA", "NWS/A", "FOXA", "EKH", "BRC", "DIN", "IHP", "MFC",
            "MKC", "MND", "NST", "RDN", "TA", "WXS", "AMX", "MMP", "WEG", "UB", "BRP", "OIHYL", "OIHYY", "OIH", "OAJ",
            "CEO", "MPX", "SJH", "THRK", "FFF", "TMW", "OEF", "MTU", "MTF", "SEM", "SLMC", "NS", "VLI", "FLO", "RTHH",
            "RTHYL", "RTH", "SAY", "SAYCY", "SFI", "BTU", "BTUUQ", "SPN", "VTI", "SCG", "MCITE", "MCWEQ", "MCIT",
            "GMRRQ", "GMR", "KFT", "MDLZ", "ADS", "STO", "ORH", "COL", "PKG", "CRYP", "CEY", "FIS", "NCF", "BG", "KMR",
            "FDG", "COC", "CHFN", "PFG", "ENB", "KB", "TEU", "MCGC", "AYI", "ACH", "RMK", "UDI", "IYZ", "IYF", "IYW",
            "IWF", "IWD", "IWV", "KT", "KTC", "HCH", "WFD", "WNEB", "SSI", "STGS", "VFGI", "JOYG", "JOY", "TCLP", "CG",
            "COTT", "COT", "IBB", "WBD", "TNP", "EPAX", "KIND", "KND", "WPPGY", "IJH", "IJK", "IJJ", "ABG", "TAP'A",
            "AAP", "GPN", "HGMCY", "HMY", "NGG", "DCM", "HHL", "PKN", "PKZ", "HHLF", "RGC", "SBS", "CPSI", "YORW",
            "UCBI", "UCBID", "IJR", "TRZ", "SJM", "TRI", "TOC", "PACR", "BGFV", "VALE", "IYY", "IVV", "IVE", "IVW",
            "IUSG", "IWZ", "IUSV", "IWW", "IJT", "IJS", "DGT", "IWP", "IWR", "IWS", "VXF", "ICF", "IYM", "IYC", "IYK",
            "IYE", "IYG", "IYH", "IYJ", "IYR", "IDU", "IGE", "IGM", "IGN", "IGW", "SOXX", "IGV", "RWR", "IXG", "EWZ",
            "EWY", "EWT", "CIT", "CITGQ", "WHG", "PCO", "TAPB", "OMG", "XEC", "MRH", "NCT", "DS", "TAYC", "WYNN", "PTP",
            "CME", "STX", "CCBI", "LQD", "RAVN", "IPCC", "ENH", "PWC", "XTF", "XTFM", "TLT", "GTM", "DWAQ", "PWO",
            "XTFQ", "IEF", "BLTI", "BLTIE", "BIOL", "AGYS", "CNO", "AGG", "SHY", "EENCD", "ENT", "EENC", "EQU", "OVNT",
            "CSE", "PJC", "CDL", "CTDBQ", "CTDB", "ERF", "PGH", "TIP", "GRP", "MIM", "GRP/U", "PFS", "ONEQ", "VBR",
            "CHE", "RRR", "EXP", "EXP'B", "EXP/B", "DADE", "AHH", "AHM", "AHMIQ", "FRO", "ABR", "GLDN", "DVY", "TSRA",
            "MTLM", "JTX", "JHTXQ", "JHTX", "MGI", "PETS", "AGO", "AIZ", "GNW", "LEN'B", "LEN/B", "NNI", "PBR'A",
            "PBR/A", "SFL", "MCIP", "TIWI", "GOGL", "VLCCF", "DPZ", "TLWT", "VMED", "NTLI", "NTLID", "WZENY", "WZEN",
            "NMTG", "NTR", "NYMT", "NMTR", "NYMO", "GPP", "GOL", "BOCH", "VNBCQ", "VNBC", "PGPDQ", "PPC", "ACC", "CNQ",
            "NYC", "NY", "SAXN", "SAX", "SAXND", "AXS", "TOPS", "TOPT", "TOPSD", "ARC", "HTH", "BBI/B", "BLOKB", "BBI'B",
            "BLOBQ", "OOO", "MOS", "LI", "PWI", "PVX", "TS", "FMD", "NP", "AIC", "IWA", "NLC", "FCL", "LVS", "PGJ",
            "PTF", "TPX", "PEY", "AEA", "MIC", "SFC", "CE", "HLF", "OXPS", "GFIG", "FTD", "BUCY", "EXE", "CXDO", "IIG",
            "WTI", "DLB", "DRYS", "MCHX", "PBW", "PWB", "PWJ", "PXMG", "PXMV", "PWP", "PXSG", "PWT", "PWV", "PWY",
            "PXSV", "ISE", "EXMCF", "EXMCQ", "EXM", "PA", "IDT", "NDAQ", "FAL", "FALB", "NRD", "XLG", "HHGP", "HSON",
            "LAZ", "MORN", "NTRI", "GSL", "NAL", "PBE", "PBJ", "PEJ", "PBS", "PXQ", "PJP", "PSI", "PSJ", "CCOI", "COI",
            "DFR", "DSW", "RSP", "RDS/B", "CRI", "RDS/A", "ITC", "IWC", "PZI", "ASEI", "CHAP", "VCR", "VDC", "VDE",
            "VFH", "VHT", "VIS", "VGT", "VAW", "VPU", "VOX", "VNQ", "VBK", "VO", "VV", "VUG", "VTV", "VB", "RUTH", "SSW",
            "JRN", "PFM", "PID", "PHJ", "ALJ", "KAR", "FDM", "AMP", "TOA", "TOUSQ", "TOUS", "VGK", "VPL", "SNN", "LUMC",
            "LUM", "LUMCE", "LUMCQ", "PXN", "PPA", "PKB", "PXE", "PXJ", "PMR", "PUI", "KFN", "PIC", "AUY", "RAIL", "SDY",
            "SLY", "DSC", "EMV", "MDYV", "EMG", "MDYG", "RSCO", "EMM", "SMD", "ELR", "ONEK", "PDS", "ICE", "PTE", "PIV",
            "SPHQ", "PHO", "ROC", "BWP", "TWGP", "DCP", "DPM", "CBS", "CBSw", "CBS/A", "RPB", "DSX", "INVA", "THRX",
            "TRX", "TRXAQ", "TROXA", "VVC", "XBI", "XHB", "XSD", "PZJ", "RPG", "RPV", "RFG", "RFV", "RZG", "RZV", "NYX",
            "AUQ", "GRS", "GNA", "FDL", "VWO", "EDR", "THI", "WNR", "AAV", "HTE", "NTLS", "NTLSD", "FPX", "ITU", "ITUB",
            "XRTX", "FNT", "HGT", "ZZ", "VIG", "POR", "ARII", "RWC", "MED", "BBD", "EQ", "GDX", "BKC", "MGG", "MA",
            "BHS", "XME", "XES", "XOP", "XPH", "XRT", "KRE", "FBT", "PWE", "CNE", "HEES", "FDV", "CMP", "DDE", "QQEW",
            "QTEC", "WYN", "UAPH", "AYR", "VOT", "VOE", "HBI", "VIAw", "VIA/Bw", "VIAB", "ACTG", "KOP", "AINV", "ADRA",
            "ADRE", "FMCN", "NMR", "IPSU", "CVY", "BLKB", "XCO", "HITT", "CTCM", "WU", "FICC", "MHL", "UTI", "FRZ",
            "RDDYQ", "RDDY", "IYT", "MWA", "SPTN", "PJB", "PYZ", "PEZ", "PSL", "PXI", "PFI", "PTH", "PRN", "PIQ", "HWCC",
            "EVX", "SLX", "PZD", "PSP", "PUW", "TCK", "TECK", "WCRX", "SBRA", "SUNH", "JPP", "VYM", "PRF", "PAC", "IDAR",
            "IAR", "IDARQ", "KBE", "KCE", "KIE", "MPW", "WLK", "WPP", "DLR", "NMX", "PJF", "PXLC", "PJG", "PXMC", "PJM",
            "PXSC", "PYH", "PGF", "TUSA", "FVI", "DTN", "DHS", "DLN", "DES", "DTD", "DON", "HRZL", "HRZLD", "HRZ", "OC",
            "FVD", "PKW", "PVM", "BTE", "CEQP", "NRGY", "LINE", "LINEQ", "GHS", "GHSE", "ETE", "SE", "NFP", "SIMO",
            "XRM", "MPG", "MPEL", "SPR", "FIG", "CNSL", "DCT", "DEI", "EROC", "OMAB", "AWH", "EIG", "VEH", "NSH", "TWC",
            "VEU", "CPA", "QMAR", "MBB", "GLS", "COHN", "AFN", "IFMI", "DSI", "IAI", "NRP", "AHGP", "DHT", "DFC",
            "DFCLQ", "HAYN", "IHF", "BND", "BSV", "BIV", "BLV", "HYG", "CQP", "KALU", "TESO", "GEO", "CVP", "KCAP",
            "USMO", "SPOK", "CPNO", "CLMT", "EEQ", "EPE", "ENLK", "XTEX", "MWE", "PVR", "RGP", "RGNC", "SXL", "USS",
            "USSPZ", "USSPQ", "MMLP", "TGP", "CNK", "HPY", "FXA", "FXB", "FXC", "FXE", "FXF", "FXM", "FXS", "FXZ", "FXL",
            "FRI", "IBKR", "NM", "NOBLQ", "NOBL", "NSANY", "GROW", "BIL", "ITE", "TLO", "IPE", "FCG", "FIW", "BEE",
            "SHO", "BX", "DFS", "TEL", "AFSI", "BMR", "ELS", "NRF", "GKD", "GKE", "FNI", "ATLS", "VEA", "BIK", "WBC",
            "ORA", "CEP", "EXH", "AROC", "BBEP", "BBEPQ", "EVEP", "LGCY", "WPZ", "CPLP", "SLT", "ESEA", "ONAVQ", "ONAV",
            "NGLS", "TMCV", "TFI", "PDQ", "PXH", "PFP", "ANW", "AFR", "AHT", "AHL", "DRH", "GLNG", "MPWR", "MUX", "UXG",
            "SCA", "SYCRF", "ATCO", "LRAD", "RSO", "TFSL", "ENP", "MZZ", "SSO", "URE", "SDS", "DIG", "DDM", "QLD", "UWM",
            "DXD", "SKF", "DUG", "QID", "SRS", "TWM", "CIG", "KBW", "DOG", "SH", "MYY", "MVV", "OZM", "GLG", "NCMI",
            "OCNFD", "OCNF", "PRGN", "PRGNF", "FXP", "EEV", "ZEP", "GA", "JNK", "MXB", "MSCI", "EDV", "CYRV", "CRZ",
            "IRC", "XIN", "GKK", "ISBC", "ITB", "PSEC", "BIP'W", "BIP", "BKD", "CIM", "CPLA", "GU", "SMN", "UYG", "EPI",
            "IAT", "PIO", "PIN", "SNX", "CEL", "SMSMY", "SMS", "PM", "CPF", "GHL", "SBLK", "HAFC", "HAFCD", "PFBC",
            "GBNK", "CBHI", "FCBP", "PACW", "PDP", "DPS", "EXR", "SNH", "WES", "VRS", "VRSZQ", "VRSZ", "CVI", "EPB",
            "IPHS", "SOA", "LO", "ENS", "TII", "TLXLY", "CDSCY", "CBY", "FSP", "FREE", "FREED", "FREEF", "SNI", "FAN",
            "AGNC", "IEO", "USD", "ROM", "MGC", "MGK", "MGV", "BNS", "HSNI", "ILG", "IILG", "IEZ", "SLH", "REW", "SSG",
            "FFNW", "CLMS", "HTS", "HTGC", "EXXIQ", "EXXI", "EXXID", "LYG", "CMF", "MUB", "NYF", "PFF", "CUK", "MDZ",
            "NDZ", "RGA/B", "IHI", "CTRN", "MVC", "LPS", "KSP", "GLAD", "FNB", "MXGL", "ALTE", "MXRE", "PUK", "OB",
            "PBNY", "ENLC", "XTXI", "DMND", "ERX", "FAS", "SPXL", "BGU", "TNA", "YSI", "CUBE", "PNFP", "UYM", "PSQ",
            "KAMN", "IVC", "CDR", "FPO", "EU", "AUNZ", "BNZ", "EDC", "EVR", "PST", "BWX", "VR", "SEA", "MJN", "TECL",
            "TYH", "ENSG", "RWM", "RWL", "LPHI", "LPHIQ", "TGH", "DNBK", "IQNT", "TNDM", "DFT", "PGX", "UXI", "WAC",
            "TYD", "TMF", "DZK", "IRET", "SEP", "GOV", "FCBC", "IEI", "TUZ", "EET", "DEP", "EBIX", "GLDD", "LINC", "NMM",
            "UPRO", "HWD", "DDC", "ABER", "EMIF", "IVR", "SIG", "DRN", "MHLD", "HEP", "PMT", "AVGO", "CSA", "STWD",
            "PDA", "BRFS", "EBRYY", "EBR", "EBR/B", "EBRBY", "ARI", "CLNY", "BSBR", "SVMLF", "FBCM", "FBRC", "TICC",
            "SAA", "GUR", "PCY", "VNR", "VALE/P", "DUF", "KS", "FSC", "BGS", "UBT", "ONP", "TQQQ", "PDM", "URTY", "UMDD",
            "UDOW", "PCEF", "BALT", "CRU", "GPRE", "CSJ", "TPIY", "TPI", "SCZ", "PRI", "SYA", "PLTM", "FTAG", "FTRI",
            "CU", "MUSA", "VIP", "GBDC", "GSM", "EXL", "PNG", "FXO", "SOXL", "NKA", "MLPN", "AMJ", "NORN", "NORNQ",
            "FAF-W", "CBOE", "SPRD", "QEP-W", "QEP", "CODI", "HPP", "PVG", "KKR", "BWXT", "CYS", "GASL", "FCGL", "CHKM",
            "ACMP", "BKCC", "IHG", "SCHR", "SCHO", "SCHP", "AMLP", "CRH", "EPM", "PHB", "CSM", "UGP", "GORO", "TWO",
            "LYB", "STON", "FMR", "CCG", "AHD", "XUE", "TAL", "CMRE", "LPLA", "BAH", "TOO", "QRE", "TLP", "SLRC", "GLP",
            "DCIX", "PZA", "FRC", "UVE", "EPU", "ORIT", "INDY", "TRGP", "BKU", "VOO", "INN", "GLPW", "ARR", "TYPE",
            "PSO", "DFJ", "DXJ", "HII", "WHXT", "WHX", "IOSP", "APO", "GNC", "UBNK", "VPFG", "LTXB", "ARCO", "UAN",
            "GMLP", "LBJ", "YINN", "CZM", "DEST", "SB", "WIBC", "TLLP", "STIR", "STAG", "TEUFF", "TEUFD", "KRO", "RLJ",
            "GRFS", "MKTX", "CCIX", "PRIM", "ECT", "CXS", "MPC", "LSE", "NMFC", "VOC", "COR", "SKYY", "SPB", "OILT",
            "DEM", "DNKN", "SXC", "AMTG", "MTGE", "WETF", "WILN", "FSR", "ACFN", "TCAP", "MAIN", "HOMB", "PIE", "CHSP",
            "PER", "UBA", "KRG", "VT", "EMB", "FBHS", "SBX", "MNR", "ORIG", "APLP", "EXLP", "CFNL", "FNV", "CSRE", "GNE",
            "XLS", "XYL", "SPLV", "LMOS", "TWIN", "RUSL", "ELD", "DGS", "NDRO", "RNF", "VAC", "DLPH", "CHKR", "IDV",
            "DWSN", "TGE", "SDT", "MN", "KBWB", "RRMS", "MEMP", "CMLP", "NRGM", "PSE", "QUAD", "MITT", "STB", "SLCA",
            "ARPJ", "ARP", "ARPJQ", "TRXT", "BOND", "HLSSF", "HLSS", "SEMG", "ALSN", "PBA", "WHZ", "WHZT", "HYD", "GLOG",
            "SIR", "RPAI", "SDR", "OAK", "PSX", "GK", "GKSR", "CLUB", "ACRE", "EVER", "PDH", "ALC", "IKGH", "AERL",
            "STBZ", "ARCT", "VCIT", "MCHI", "CLDT", "BKW", "TROX", "WMLP", "OXF", "OTT", "TAHO", "HDV", "EQM", "HTA",
            "INTX", "MCEP", "ROYT", "CIU", "MANU", "VCLT", "IFGL", "ATAX", "TLH", "EMLC", "EFC", "RNO", "RHNOD", "RHNO",
            "MVO", "HOFT", "FF", "EPHC", "CORE", "SRC", "HCI", "HCII", "ADT", "KRFT", "SMLP", "SUSP", "WPC", "LBAI",
            "BDCV", "KIPO", "XRDC", "FHCO", "CSFL", "BNCL", "RLGY", "LNCOQ", "LNCO", "CYCC", "VXUS", "SDLP", "GAIN",
            "DKL", "JE", "HCLP", "ALDW", "MCC", "RESI", "RESIw", "SCHD", "HYLD", "JXI", "ABBV", "FDUS", "CORR", "RNST",
            "PSTB", "FSCI", "FUBC", "NXST", "VSS", "ZROZ", "HYS", "CVRR", "USAC", "VNQI", "SCHM", "BKLN", "FTC", "NFBK",
            "TMS", "HRZN", "ZTS", "SXCP", "NGL", "EWX", "EDIV", "SCHH", "STNG", "WSR", "FORX", "IEMG", "IEFA", "IEP",
            "ARCP", "VER", "AAPL7", "APAM", "BSRR", "EEMV", "EFAV", "MPLX", "IBCA", "BKEP", "BFIN", "AVIV", "WSTC",
            "GWL", "GLDI", "DRD", "PF", "BPY", "LTPZ", "SDIV", "KNOP", "EVTC", "SEAS", "CST", "HASI", "VOYA", "CBF",
            "DBJP", "CWB", "NRZ", "MDIV", "TEP", "ARPI", "TUR", "DGRW", "TCPC", "DMB", "DBEF", "COTY", "SCM", "SSB",
            "SCBT", "MCBC", "GOOD", "ADK", "BHLB", "LMNR", "BTT", "CDW", "JPNS", "CSG", "JMI", "COLE", "AMRE", "PIZ",
            "LEMB", "SPHB", "SJNK", "BNDX", "DXJS", "NYLD/A", "NYLD", "MUNI", "DWAS", "EBND", "VTWO", "REXR", "DOC",
            "PSXP", "AMH", "ASC", "YDKN", "PFLT", "DFZ", "QEPM", "FI", "IPFF", "EMES", "SSLT", "VEDL", "QIWI", "FIBK",
            "EELV", "SAIC", "MYCC", "VET", "PEGI", "HYMB", "ESRT", "OCIP", "JNUG", "JDST", "BAGL", "QTS", "FXH", "FXR",
            "MLPX", "PAGP", "WNRL", "GLPI", "CLY", "IGOV", "BRX", "REZ", "GVI", "CFT", "CRED", "CXP", "IHY", "LBMH",
            "ALLE", "MEP", "DLNG", "AAL", "IXUS", "DFE", "ARMK", "VLP", "AMC", "HOME", "GNR", "FEP", "OGS", "SWAY",
            "SFR", "THD", "RWK", "RWJ", "NEWM", "GCAP", "KYN", "NADL", "FEM", "HKOR", "TLMR", "WSBF", "ALLY", "ENBL",
            "NAVI", "NYRT", "SABR", "RCKB", "ARES", "CSBK", "FSIC", "PBFX", "WPG", "FV", "CVEO", "HCT", "TIME", "SILJ",
            "TOWR", "BRSS", "RYAM", "TMST", "NSAM", "FELP", "PAHC", "FLOT", "SCPB", "SHM", "VCSH", "OAKS", "BNCN",
            "TERP", "SHV", "PHDG", "MLPI", "MINT", "IMLP", "EMLP", "PGNPF", "PGNPQ", "FDD", "FEX", "ITM", "TDTT", "SYF",
            "RCAPQ", "RCAP", "TPUB", "TRNC", "WLKP", "RIGP", "AMID", "GSJK", "CCLP", "CAPL", "LGP", "NEP", "NSLP",
            "NSLPQ", "WGP", "VRTS", "VTTI", "HMLP", "EBSB", "CDK", "CFG", "NGHC", "TVPT", "VNOM", "ICL", "SNR", "SHLX",
            "KWEB", "HACK", "STOR", "CRC", "BHBK", "AMFW", "TRCO", "RMP", "REMY", "MORE", "CNNX", "CPPL", "DBEU", "HEFA",
            "QADA", "DM", "JMG", "VIRT", "CSAL", "NSA", "BSM", "CPG", "TEGP", "EQGP", "HNRG", "FTAI", "KRNY", "AZURQ",
            "AZUR", "HEWJ", "HEZU", "HEWG", "BXLT", "CPGX", "WRK", "CAFD", "KHC", "FENY", "FNCL", "FHLC", "FTEC", "FCA",
            "FNDX", "EUSC", "IPAY", "QUAL", "CIBR", "OMAM", "OUSA", "GLBL", "APLE", "CCP", "RYH", "IHE", "VRP", "TIER",
            "IHDG", "HLI", "PSCH", "FNHC", "JRVR", "TSLX", "QQQE", "XLFS", "CXRX", "FMAT", "HPE", "NRE", "RINF", "CNOB",
            "GSIE", "GEM", "FBNK", "CZNC", "GSLC", "FLIC", "FSFR", "GWB", "HRTG", "LMAT", "MBTF", "MRCC", "NEWT", "SFBS",
            "SFNC", "SYBT", "TOWN", "BDGE", "CPTA", "CRWS", "CVCY", "FMNB", "FNLC", "GARS", "HBNC", "MBWM", "SLP",
            "SUNS", "TIS", "TPVG", "CSRA", "FBIZ", "MRLN", "REIS", "SGBK", "ABDC", "ACSF", "DGICA", "DRAD", "EFSC",
            "HTLF", "UVSP", "BITE", "BCBP", "BSF", "CMFN", "IBTX", "OPB", "PGC", "RFIL", "TBNK", "UDF", "WTBA", "WMS",
            "RETL", "MXI", "SRG", "OEC", "RXL", "GNL", "SPHD", "BATS", "ENIC", "MGP", "CIO", "IRT", "NBHC", "ORC", "TSE",
            "FGL", "GLOP", "APTS", "JPEP", "NXRT", "EVA", "FPI", "NAP", "NAO", "FTV", "DEA", "TRTN", "LOB", "QABA",
            "ANGL", "APFH", "FHB", "USDP", "SRLP", "AMOT", "SMDV", "REGL", "VVV", "LKSD", "FTS", "EURN", "ARNC", "LW",
            "XAR", "SNLN", "FPE", "LMRK", "CLNS"
        };
    }
}
